from .data_e_hora import DataHora
from .manipulacao_arquivos import ManipulacaoArquivos
from .numero_documento import ValidaDocs
from .telefone import Tels
from .valores_monetarios import ValoresMonetarios
from .validador_formularios import ValidaForms
from .extracao_texto_nota_fiscal import ExtrairTextoNotaFiscal
from .extracao_nfs_e import ExtrairDadosNFSe
from .gameficacao import Gameficacao
from .utilitario_semanal import UtilitariosSemana
from .processador_arquivo_ofx import OFXProcessor
from .extracao_texto_ticket import ExtracaoTicket